export const fullNames = [
    "Splash Mob",
    "Deep Blue",
    "Hook Line and Inker",
    "Squid Pro Quo",
    "Judd Dread",
    "Squids Next Door",
    "Assault and Pepper",
    "Crab Rave",
    "Cheese Returns",
    "Brine Blast",
    "Notorious I.N.K.",
    "Flubber Duckies",
    "Inkquisition",
    "Inksidious",
    "InkSync",
    "Instant Ramen",
    "Just Inkcase",
    "Just Squidding",
    "Koi Pond",
    "New Squids on the Dock",
    "Nothin' Personnel Squid",
    "Original Name",
    "Names Are hard",
    "Rain and Sqwiffering",
    "S.P.L.A.T Team One",
    "Tako Yaki",
    "Send Kelp",
    "Sour Patch Squids",
    "Star Splatinum",
    "Squidlife Chrisis",
    "Over the Transom",
    "Kraken the Hull",
    "That's a Lot of Clamage",
    "That Ship Has Sailed",
    "Thin Ice",
    "Landlubbers",
    "Fish out of Water",
    "The Only Fish in the Sea",
    "Panic at the Grisco",
    "Dredgelords",
    "Boaty McBoatface",
    "Sailmates",
    "Shipload of Trouble",
    "No Wake Zone",
    "What Does This Button Do",
    "Seadonists",
    "Four Squids in a Trenchcoat",
    "Just for the Halibut",
    "Memento Mori",
    "Sponsored By Raid Shadow Legends",
    "Chum Lords",
    "Stream Team",
    "The Hidden Ink Village",
    "Unopened Callie Amiibo",
    "Gurren Lagoon",
    "Ink Floyd",
    "Meme Team",
];
