export const suffixes = [
    "Woomies",
    "Army",
    "Squad",
    "Allegiance",
    "Blue",
    "Crew",
    "Angels",
    "Squids",
    "Gamers",
    "Moon",
    "Pacific",
    "Lobsters",
    "Gang",
    "Infinity",
    "Agents",
    "Kids",
    "Ink",
    "Flow",
    "Wolves",
    "Mania",
    "Junior",
    "In Paradise",
    "Tide",
    "Breakers",
    "Rays",
    "Tank",
    "Herd",
    "School",
    "Shoal",
    "Hawks",
    "Shade",
    "Blast",
    "Bento",
    "Shore",
    "Bops",
    "Ninjas",
    "Uprising",
    "Logic",
    "Quad",
    ".EXE",
    ".com",
    "Dudes",
    "Gals",
    "Nest",
    "Kois",
    "of the Week",
    "Republic",
    "Rivals",
    "Inferno",
    "Wave",
    "Dragons",
    "Bait",
    "Profreshionals",
    "Sirens",
    "Seals",
    "Attacc",
    "Crest",
    "Strikers",
    "Galaxy",
    "Anonymous",
    "Elites",
    "Inkcorporated",
    "for Days",
    "Urchins",
    "Returns",
    "Anglers",
    "Empire",
    "Pirates",
    "Hurricane",
    "Tornado",
    "For Hire",
    "Incarnate",
    "Knights",
    "Season",
    "Fury",
    "Forge",
    "Rollers",
    "Machine",
    "and Friends",
    "Mates",
    "Thunder",
    "Test Subjects",
    "Mob"
]


export const extraSuffixes = [
    "of America",
    "( TM )",
    "of Michigan",
    "and Company",
    "but, like, cooler",
    "by Nintendo",
]
